# ********RoostGPT********
"""
Test generated by RoostGPT for test pyArrayDSTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=is_monotonic_c787c79d3e
ROOST_METHOD_SIG_HASH=is_monotonic_5e916fe8f2


Scenario 1: List with Increasing Monotonic Sequence
Details:
  TestName: test_increasing_monotonic_sequence
  Description: Verify that the function returns `True` when the input list represents an increasing monotonic sequence.
Execution:
  Arrange: Prepare a list of integers in increasing order, e.g., [1, 2, 3, 4, 5].
  Act: Pass the list as an argument to the `is_monotonic` function.
  Assert: The result should be `True`.
Validation:
  Rationalize the importance of testing that the function correctly identifies increasing monotonic sequences, aligning with one half of its core logic.

Scenario 2: List with Decreasing Monotonic Sequence
Details:
  TestName: test_decreasing_monotonic_sequence
  Description: Verify that the function returns `True` when the input list represents a decreasing monotonic sequence.
Execution:
  Arrange: Prepare a list of integers in decreasing order, e.g., [5, 4, 3, 2, 1].
  Act: Pass the list as an argument to the `is_monotonic` function.
  Assert: The result should be `True`.
Validation:
  Rationalize why testing decreasing monotonic sequences ensures the correctness of the other half of the core logic.

Scenario 3: List with Non-Monotonic Sequence
Details:
  TestName: test_non_monotonic_sequence
  Description: Verify that the function returns `False` when the input list does not represent a monotonic sequence.
Execution:
  Arrange: Prepare a list of integers that neither increase nor decrease throughout, e.g., [1, 3, 2, 4].
  Act: Pass the list as an argument to the `is_monotonic` function.
  Assert: The result should be `False`.
Validation:
  Rationalize the significance of testing non-monotonic sequences to ensure the function correctly rejects lists that are not monotonic.

Scenario 4: List with Constant Sequence Values
Details:
  TestName: test_constant_sequence
  Description: Verify that the function returns `True` when all values in the list are the same, as this satisfies monotonic conditions.
Execution:
  Arrange: Prepare a list where all elements are identical, e.g., [3, 3, 3, 3].
  Act: Pass the list as an argument to the `is_monotonic` function.
  Assert: The result should be `True`.
Validation:
  Rationalize that constant lists represent edge cases in monotonic behavior, which the function should correctly classify as monotonic.

Scenario 5: Empty List Input
Details:
  TestName: test_empty_list
  Description: Verify that the function handles an empty list gracefully, returning `True`, as an empty list can be considered trivially monotonic.
Execution:
  Arrange: Prepare an empty list, e.g., [].
  Act: Pass the empty list as an argument to the `is_monotonic` function.
  Assert: The result should be `True`.
Validation:
  Rationalize the importance of testing edge cases like empty lists to ensure robust handling by the function.

Scenario 6: List with Single Element
Details:
  TestName: test_single_element_list
  Description: Verify that the function returns `True` for a list with a single element, as this satisfies monotonic conditions.
Execution:
  Arrange: Prepare a list with one integer, e.g., [7].
  Act: Pass the single-element list as an argument to the `is_monotonic` function.
  Assert: The result should be `True`.
Validation:
  Rationalize the necessity of testing single-element lists to cover trivial edge cases within the function's logic.

Scenario 7: List with Duplicate Values in Monotonic Sequence
Details:
  TestName: test_monotonic_sequence_with_duplicates
  Description: Verify that the function correctly handles sequences containing duplicate values while maintaining monotonicity.
Execution:
  Arrange: Prepare a list with repeated values in a monotonic order, e.g., [1, 1, 2, 2, 3].
  Act: Pass the list as an argument to the `is_monotonic` function.
  Assert: The result should be `True`.
Validation:
  Rationalize the importance of testing duplicates within monotonic sequences to ensure robustness in the function's logic.

Scenario 8: Large List with Monotonic Sequence
Details:
  TestName: test_large_monotonic_list
  Description: Verify that the function efficiently handles and returns `True` for large monotonic sequences.
Execution:
  Arrange: Prepare a large list with integers in increasing order, e.g., [1, 2, 3, ..., 100000].
  Act: Pass the list as an argument to the `is_monotonic` function.
  Assert: The result should be `True`.
Validation:
  Rationalize the necessity of testing large lists to confirm the scalability and performance of the function.

Scenario 9: Large List with Non-Monotonic Sequence
Details:
  TestName: test_large_non_monotonic_list
  Description: Verify that the function correctly handles and returns `False` for a large non-monotonic sequence.
Execution:
  Arrange: Prepare a large list with values that fluctuate, e.g., [1, 2, 3, ..., 99999, 50000].
  Act: Pass the list as an argument to the `is_monotonic` function.
  Assert: The result should be `False`.
Validation:
  Rationalize the importance of testing large non-monotonic sequences for correctness under high input volumes.

Scenario 10: List with Only Two Elements
Details:
  TestName: test_two_element_list
  Description: Verify that the function handles the smallest possible non-empty list correctly. The list should be considered monotonic.
Execution:
  Arrange: Prepare a list with two integers in ascending or descending order, e.g., [10, 20] or [20, 10].
  Act: Pass the list as an argument to the `is_monotonic` function.
  Assert: The result should be `True`.
Validation:
  Rationalize testing two-element lists as an essential edge case to verify the correctness of the function for minimal input sizes.

"""

# ********RoostGPT********
import pytest
from monotonic_array import is_monotonic

@pytest.mark.valid
class Test_MonotonicArrayIsMonotonic:
    @pytest.mark.smoke
    @pytest.mark.positive
    def test_increasing_monotonic_sequence(self):
        # Arrange
        increasing_list = [1, 2, 3, 4, 5]
        # Act
        result = is_monotonic(increasing_list)
        # Assert
        assert result is True

    @pytest.mark.smoke
    @pytest.mark.positive
    def test_decreasing_monotonic_sequence(self):
        # Arrange
        decreasing_list = [5, 4, 3, 2, 1]
        # Act
        result = is_monotonic(decreasing_list)
        # Assert
        assert result is True

    @pytest.mark.regression
    @pytest.mark.negative
    def test_non_monotonic_sequence(self):
        # Arrange
        non_monotonic_list = [1, 3, 2, 4]
        # Act
        result = is_monotonic(non_monotonic_list)
        # Assert
        assert result is False

    @pytest.mark.regression
    @pytest.mark.edgecase
    def test_constant_sequence(self):
        # Arrange
        constant_list = [3, 3, 3, 3]
        # Act
        result = is_monotonic(constant_list)
        # Assert
        assert result is True

    @pytest.mark.regression
    @pytest.mark.edgecase
    def test_empty_list(self):
        # Arrange
        empty_list = []
        # Act
        result = is_monotonic(empty_list)
        # Assert
        assert result is True

    @pytest.mark.regression
    @pytest.mark.edgecase
    def test_single_element_list(self):
        # Arrange
        single_element_list = [7]
        # Act
        result = is_monotonic(single_element_list)
        # Assert
        assert result is True

    @pytest.mark.regression
    @pytest.mark.valid
    def test_monotonic_sequence_with_duplicates(self):
        # Arrange
        duplicate_monotonic_list = [1, 1, 2, 2, 3]
        # Act
        result = is_monotonic(duplicate_monotonic_list)
        # Assert
        assert result is True

    @pytest.mark.performance
    @pytest.mark.valid
    def test_large_monotonic_list(self):
        # Arrange
        large_monotonic_list = list(range(1, 100001))  # TODO: Adjust size if needed
        # Act
        result = is_monotonic(large_monotonic_list)
        # Assert
        assert result is True

    @pytest.mark.performance
    @pytest.mark.negative
    def test_large_non_monotonic_list(self):
        # Arrange
        large_non_monotonic_list = list(range(1, 99999)) + [50000]  # TODO: Adjust values if needed
        # Act
        result = is_monotonic(large_non_monotonic_list)
        # Assert
        assert result is False

    @pytest.mark.regression
    @pytest.mark.valid
    def test_two_element_list(self):
        # Arrange
        two_element_ascending = [10, 20]
        two_element_descending = [20, 10]
        # Act
        result_ascending = is_monotonic(two_element_ascending)
        result_descending = is_monotonic(two_element_descending)
        # Assert
        assert result_ascending is True
        assert result_descending is True
