# ********RoostGPT********
"""
Test generated by RoostGPT for test pyArrayDSTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=is_monotonic_c787c79d3e
ROOST_METHOD_SIG_HASH=is_monotonic_5e916fe8f2


```
Scenario 1: Test with a list in ascending order
Details:
  TestName: test_monotonic_ascending_order_list
  Description: The test should check if the provided list is in strictly increasing order thus depicting the function's ability to identify monotonic ascending sequences.
Execution:
  Arrange: A list of integers in ascending order is initialized.
  Act: The function is_monotonic is invoked with the ascending list as the parameter.
  Assert: The expected outcome is True since the list is in ascending order.
Validation:
  This test is important to validate that the function correctly identifies monotonic sequences in ascending order. This is a base scenario to validate the function against the requirement of identifying ascending ordered lists.

Scenario 2: Test with a list in descending order
Details:
  TestName: test_monotonic_descending_order_list
  Description: This test checks if the function is able to identify a descending ordered list as monotonic.
Execution:
  Arrange: A list of integers in descending order is initialized.
  Act: The function is_monotonic is invoked with the descending list as the parameter.
  Assert: The expected outcome is True since the input is a monotonic sequence with descending order.
Validation:
  This test is crucial to certify function's ability to recognize sequences that descend or remain constant. It helps to ascertain that the function adheres to monotonic sequence definition.

Scenario 3: Test with a non-monotonic list
Details:
  TestName: test_non_monotonic_list
  Description: The test is intended to validate the function's ability to identify a non-monotonic list.
Execution:
  Arrange: A list of integers that is neither strictly increasing nor decreasing is initialized.
  Act: The function is_monotonic is invoked with the non-monotonic list as the parameters.
  Assert: The expected outcome is False since the list is not in a strictly increasing or decreasing order.
Validation:
  This test is essential to ensure that the function accurately identifies non-monotonic sequences, thus confirming its ability to distinguish between monotonic and non-monotonic sequences.

Scenario 4: Test with a list of identical numbers
Details:
  TestName: test_identical_numbers_list
  Description: This test aims to check the function's performance when provided with a list of identical numbers.
Execution:
  Arrange: A list of identical integers is created.
  Act: The method is_monotonic is called with the list of identical numbers.
  Assert: The expected outcome is True, as a list of identical numbers is considered monotonic.
Validation:
  This scenario is valuable to verify the element-based comparison logic used in the function and assure that identical numbers are treated as valid monotonic sequences.

Scenario 5: Test with an empty list
Details:
  TestName: test_empty_list
  Description: The test should validate the function's behavior when an empty list is passed.
Execution:
  Arrange: An empty list is initialized.
  Act: The function is_monotonic is called with the empty list.
  Assert: The expected result is True - an empty list is considered monotonic as there are no elements violating the monotonic property.
Validation:
  This test is key in asserting whether the function handles edge cases appropriately, specifically acknowledging that in absence of any elements, no violation of the monotonic property is possible. 
```
"""

# ********RoostGPT********
import pytest
from monotonic_array import is_monotonic

class Test_MonotonicArrayIsMonotonic:
    def test_monotonic_ascending_order_list(self):
        retrieval = is_monotonic([1, 2, 2, 3])
        assert retrieval == True

    def test_monotonic_descending_order_list(self):
        retrieval = is_monotonic([6, 5, 4, 4])
        assert retrieval == True

    def test_non_monotonic_list(self):
        retrieval = is_monotonic([1, 3, 2])
        assert retrieval == False

    def test_identical_numbers_list(self):
        retrieval = is_monotonic([4, 4, 4, 4])
        assert retrieval == True

    def test_empty_list(self):
        retrieval = is_monotonic([])
        assert retrieval == True
