# ********RoostGPT********
"""
Test generated by RoostGPT for test pyArrayDSTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=query_d0f7abcd9c
ROOST_METHOD_SIG_HASH=query_cf3af96663


Scenario 1: Query on a non-empty list with valid bounds
Details:
  TestName: test_query_on_nonempty_list_valid_bounds
  Description: This test is intended to verify that the query function returns the correct minimum value within the given valid bounds for a non-empty list.
Execution:
  Arrange: Create a sparse table from a non-empty list.
  Act: Invoke the function with the sparse table and valid bounds.
  Assert: Check that the function returns the expected minimum value within the bounds.
Validation:
  This test ensures that the function correctly finds the minimum value within the given valid bounds in a non-empty list, which is central to its business logic.

Scenario 2: Query on non-empty list with invalid bounds
Details:
  TestName: test_query_on_nonempty_list_invalid_bounds
  Description: This test is intended to verify that the query function raises an IndexError when provided with invalid bounds on a non-empty list.
Execution:
  Arrange: Create a sparse table from a non-empty list.
  Act: Invoke the function with the sparse table and invalid bounds.
  Assert: Check that the function raises an IndexError.
Validation:
  This test ensures that the function correctly throws an error when given invalid bounds, which is a crucial part of its error handling behavior.

Scenario 3: Query on an empty list
Details:
  TestName: test_query_on_empty_list
  Description: This test is intended to verify that the query function raises a ValueError when provided with an empty list.
Execution:
  Arrange: Create a sparse table from an empty list.
  Act: Invoke the function with the sparse table.
  Assert: Check that the function raises a ValueError.
Validation:
  Passing an empty list into the function is not a valid operation as per the business logic, thus, this validates that the function correctly throws an error in this scenario.

Scenario 4: Query on single element list
Details:
  TestName: test_query_on_single_element_list
  Description: This test is to verify that the query function returns the single element when provided with a one-element list and valid bounds.
Execution:
  Arrange:  Create a sparse table from a one-element list.
  Act: Invoke the function with the sparse table and valid bounds.
  Assert: Check that the function returns the single element in the list.
Validation:
  This test assures that the function can handle edge cases like single-element lists. Even though this is not the main function of the business logic, validating this enhances the robustness of the function.
"""

# ********RoostGPT********
import pytest
from math import log2
from sparse_table import query, build_sparse_table

class Test_SparseTableQuery:

    def test_query_on_nonempty_list_valid_bounds(self):
        non_empty_list = [8, 1, 0, 3, 4, 9, 3]
        left_bound, right_bound = 0, 4
        sparse_table = build_sparse_table(non_empty_list)
        assert query(sparse_table, left_bound, right_bound) == 0

    def test_query_on_nonempty_list_invalid_bounds(self):
        non_empty_list = [8, 1, 0, 3, 4, 9, 3]
        left_bound, right_bound = 0, 11
        sparse_table = build_sparse_table(non_empty_list)
        with pytest.raises(IndexError):
            query(sparse_table, left_bound, right_bound)
    
    def test_query_on_empty_list(self):
        empty_list = []
        left_bound, right_bound = 0, 0 
        sparse_table = build_sparse_table(empty_list)
        with pytest.raises(ValueError):
            query(sparse_table, left_bound, right_bound)

    def test_query_on_single_element_list(self):
        single_element_list = [3]
        left_bound, right_bound = 0, 0
        sparse_table = build_sparse_table(single_element_list)
        assert query(sparse_table, left_bound, right_bound) == 3