[pytest]
markers =
    regression: mark a test as regression scenario
    valid: mark a test as valid scenario
    empty: mark a test as empty scenario
    missing: mark a test as missing scenario
    invalid: mark a test as invalid scenario
    positive: mark a test as positive scenario
    negative: mark a test as negative scenario
    smoke: mark a test as smoke scenario
    edge: mark a test as edge scenario
    zeroed: mark a test as zeroed scenario
    performance: mark a test as performance scenario
    security: mark a test as security scenario
    parametrize: mark a test as parametrize scenario
    random: mark a test as random scenario
