[pytest]
markers =
    regression: mark a test as regression scenario
    valid: mark a test as valid scenario
    negative: mark a test as negative scenario
    parametrize: mark a test as parametrize scenario
    positive: mark a test as positive scenario
    smoke: mark a test as smoke scenario
    edge: mark a test as edge scenario
    addtag: mark a test as addtag scenario
    performance: mark a test as performance scenario
    edgecase: mark a test as edgecase scenario
    exception: mark a test as exception scenario
    capture_stdout: mark a test as capture_stdout scenario
