# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonunittesting1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=calc_profit_b5630eec64
ROOST_METHOD_SIG_HASH=calc_profit_d387a7f844


```
Scenario 1: Testing the function with positive profits and weights.
Details:
  TestName: test_positive_profits_weights
  Description: This test is intended to verify that the function returns the correct profit when all profits and weights are positive.
Execution:
  Arrange: Initialize profits and weights as lists of positive integers. Set max_weight as a positive integer.
  Act: Invoke the function calc_profit with the initialized profits, weights, and max_weight.
  Assert: Check that the returned profit is as expected.
Validation:
  This test is important as it checks the basic functionality of the function with the most common type of input, positive profits and weights.

Scenario 2: Testing the function with zero in profits and weights.
Details:
  TestName: test_zero_profits_weights
  Description: This test is intended to verify that the function raises a ValueError when any profit or weight is zero.
Execution:
  Arrange: Initialize profits and weights as lists containing zero. Set max_weight as a positive integer.
  Act: Invoke the function calc_profit with the initialized profits, weights, and max_weight.
  Assert: Check that a ValueError is raised.
Validation:
  This test is important as it checks that the function correctly handles the edge case where a profit or weight is zero.

Scenario 3: Testing the function with negative profits and weights.
Details:
  TestName: test_negative_profits_weights
  Description: This test is intended to verify that the function raises a ValueError when any profit or weight is negative.
Execution:
  Arrange: Initialize profits and weights as lists containing negative integers. Set max_weight as a positive integer.
  Act: Invoke the function calc_profit with the initialized profits, weights, and max_weight.
  Assert: Check that a ValueError is raised.
Validation:
  This test is important as it checks that the function correctly handles the edge case where a profit or weight is negative.

Scenario 4: Testing the function with max_weight being zero.
Details:
  TestName: test_zero_max_weight
  Description: This test is intended to verify that the function raises a ValueError when max_weight is zero.
Execution:
  Arrange: Initialize profits and weights as lists of positive integers. Set max_weight as zero.
  Act: Invoke the function calc_profit with the initialized profits, weights, and max_weight.
  Assert: Check that a ValueError is raised.
Validation:
  This test is important as it checks that the function correctly handles the edge case where max_weight is zero.

Scenario 5: Testing the function with profits and weights of different lengths.
Details:
  TestName: test_different_length_profits_weights
  Description: This test is intended to verify that the function raises a ValueError when the lengths of profits and weights are different.
Execution:
  Arrange: Initialize profits and weights as lists of different lengths. Set max_weight as a positive integer.
  Act: Invoke the function calc_profit with the initialized profits, weights, and max_weight.
  Assert: Check that a ValueError is raised.
Validation:
  This test is important as it checks that the function correctly handles the edge case where profits and weights are of different lengths.
```

"""

# ********RoostGPT********
import pytest
from knapsack.greedy_knapsack import calc_profit


class Test_GreedyKnapsackCalcProfit:
    @pytest.mark.regression
    def test_positive_profits_weights(self):
        profits = [5, 8, 7, 1, 12, 3, 4]
        weights = [2, 7, 1, 6, 4, 2, 5]
        max_weight = 100
        expected_profit = 166.5
        assert calc_profit(profits, weights, max_weight) == expected_profit

    @pytest.mark.negative
    def test_zero_profits_weights(self):
        profits = [0, 0, 0, 0, 0]
        weights = [0, 0, 0, 0, 0]
        max_weight = 100
        with pytest.raises(ValueError):
            calc_profit(profits, weights, max_weight)

    @pytest.mark.negative
    def test_negative_profits_weights(self):
        profits = [-1, -2, -3, -4, -5]
        weights = [-1, -2, -3, -4, -5]
        max_weight = 100
        with pytest.raises(ValueError):
            calc_profit(profits, weights, max_weight)

    @pytest.mark.negative
    def test_zero_max_weight(self):
        profits = [5, 8, 7, 1, 12, 3, 4]
        weights = [2, 7, 1, 6, 4, 2, 5]
        max_weight = 0
        with pytest.raises(ValueError):
            calc_profit(profits, weights, max_weight)

    @pytest.mark.negative
    def test_different_length_profits_weights(self):
        profits = [5, 8, 7, 1, 12, 3, 4]
        weights = [2, 7, 1, 6, 4, 2]
        max_weight = 100
        with pytest.raises(ValueError):
            calc_profit(profits, weights, max_weight)
