# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=maxpooling_f4c12bf153
ROOST_METHOD_SIG_HASH=maxpooling_4f9b1c141c


```
Scenario 1: Testing the maxpooling function with a square matrix, where size and stride are non-negative integers
Details:
  TestName: test_maxpooling_valid_input
  Description: This test verifies that the maxpooling function works correctly with a square matrix, where size and stride are non-negative integers
Execution:
  Arrange: We initialize a square matrix along with valid size and stride inputs. 
  Act: We call the maxpooling function with the initialized matrix and size, stride values. 
  Assert: We check that the output from the function matches the expected output matrix.
Validation:
  As the primary function of the maxpool operation is to reduce the input dimensionality while retaining the most important information, this test validates how well our function is performing this operation. This expected behaviour is crucial for the function to be used effectively in image processing and matrix manipulations.

Scenario 2: Testing the maxpooling function with a non-square matrix
Details:
  TestName: test_maxpooling_non_square_matrix
  Description: This test verifies that the maxpooling function raises a ValueError when the input is a non-square matrix.
Execution:
  Arrange: We prepare a non-square matrix. 
  Act: We call the maxpooling function with this non-square matrix and any valid size and stride values. 
  Assert: We check that a ValueError with the appropriate message is raised when we call the function.
Validation:
  This test is important because, by design, the maxpooling function is meant to work with square matrices and a well-defined business logic should alert the user about the non-compliant inputs. 

Scenario 3: Testing the maxpooling function with a square matrix but with the stride larger than the size of the matrix
Details:
  TestName: test_maxpooling_stride_larger_than_matrix_size
  Description: This test is intended to verify that the maxpooling function returns a zero-valued matrix if the stride is larger than size of the matrix.
Execution:
  Arrange: We initialize a square matrix and size, stride values where stride is larger than matrix size. 
  Act: Then, we call the maxpooling function with these values.
  Assert: We check that the output from the function is a zero-valued matrix.
Validation:
  This test is important because stride larger than matrix size will result in no shifts over the matrix, which means no valid maxpool operation can be performed. In this case, the function should return a zero-valued matrix as the output.

Scenario 4: Testing the maxpooling function with a square matrix and with the stride larger than the size of the kernel
Details:
  TestName: test_maxpooling_stride_larger_than_kernel_size
  Description: This test is intended to verify that the maxpooling function executes properly with valid input where stride is larger than the kernel size.
Execution:
  Arrange: We initialize a square matrix and size, stride values where the stride is larger than size.
  Act: We call the maxpooling function with these initialized values.
  Assert: We check the output from the function equals expected output matrix. 
Validation:
  In some scenarios, a stride larger than the kernel size is used to have a more aggressive downsampling. This test ensures if the function can effectively handle such cases by skipping the unnecessary data and retaining the most important values.
```

"""

# ********RoostGPT********
import numpy as np
import pytest
from pooling_functions import maxpooling

class Test_PoolingFunctionsMaxpooling:
    def test_maxpooling_valid_input(self):
        arr = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
        size = 2
        stride = 2
        expected = np.array([[6., 8.],[14., 16.]])

        result = maxpooling(arr, size, stride)

        np.testing.assert_array_equal(result, expected)

    def test_maxpooling_non_square_matrix(self):
        arr = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

        with pytest.raises(ValueError) as exe_info:
            maxpooling(arr, 2, 2)

        assert str(exe_info.value) == "The input array is not a square matrix"

    def test_maxpooling_stride_larger_than_matrix_size(self):
        arr = [[10, 20], [30, 40]]
        size = 2
        stride = 3
        expected = np.zeros((0, 0))

        result = maxpooling(arr, size, stride)

        np.testing.assert_array_equal(result, expected)

    def test_maxpooling_stride_larger_than_kernel_size(self):
        arr = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]
        size = 2
        stride = 4
        expected = np.array([[12, 16],[32,36]])

        result = maxpooling(arr, size, stride)

        np.testing.assert_array_equal(result, expected)
