# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=update_image_and_anno_ea2559529d
ROOST_METHOD_SIG_HASH=update_image_and_anno_69363f2c89


```python
Scenario 1: Test when the input annotations are empty.
Details:
  TestName: test_update_image_and_anno_with_empty_annotations
  Description: The test is intended to verify that the function properly handles empty annotation sets. 
Execution:
  Arrange: Prepare an image list, an empty annotations list, a set of indexes, output size, scale range, and filter scale.
  Act: Call the update_image_and_anno() function with these parameters.
  Assert: Check if the function returns an image with no annotations.
Validation:
  Rationale: If the function behaves as expected with an empty annotation set, it ensures that it doesn't blindly depend on annotations to perform its tasks.

Scenario 2: Test resizing and scaling of the image.
Details:
  TestName: test_resizing_and_scaling
  Description: The test is intended to verify that the output image size and the new annotation coordinates match the expected value after applying the resizing and scaling.
Execution:
  Arrange: Prepare an image list, annotations list, set of indexes, output size, scale range, and filter scale.
  Act: Call the update_image_and_anno() function, and check the size of the output image and the new annotations.
  Assert: The size of the output image should match the provided output size, and annotations should be correctly scaled.
Validation:
  Rationale: Ensuring that the image resize and scale parameters are correctly applied provides confidence in the function's core operation.

Scenario 3: Test behavior of function with different filter scales
Details:
  TestName: test_different_filter_scales
  Description: This test is responsible for verifying that the function correctly filters bounding boxes of scales smaller than provided filter scale.
Execution:
  Arrange: Prepare an image list, annotations list, set of indexes, output size, scale range, and different filter scales.
  Act: Call the update_image_and_anno() function with these parameters and different filter scales.
  Assert: Check if the function filters out bounding boxes of scales smaller than the filter scale.
Validation:
  Rationale: Checking the function's behavior against different filter scales ensures that it correctly filters bounding boxes.

Scenario 4: Test processing of different quadrant annotations
Details:
  TestName: test_quadrant_annotations
  Description: This test is to verify that the function correctly processes annotations for each quadrant.
Execution:
  Arrange: Prepare an image list, annotations list (each for the specific quadrant), set of indexes, output size, scale range, and filter scale.
  Act: Call the update_image_and_anno() function with these parameters.
  Assert: Check if the function places and scales the annotations correctly for each quadrant.
Validation:
  Rationale: Ensuring correct processing of quadrant annotations verifies the function's capability to handle multi-quadrant image data.
```
"""

# ********RoostGPT********
import pytest
import cv2
import numpy as np
import random
from mosaic_augmentation import update_image_and_anno

class Test_MosaicAugmentationUpdateImageAndAnno:

    def test_update_image_and_anno_with_empty_annotations(self):
        img_list = ['image1.jpg', 'image2.jpg', 'image3.jpg', 'image4.jpg']
        empty_annos = [[], [], [], []]
        idxs = [0,1,2,3]
        output_size = (720,1280)
        scale_range = (0.4, 0.6)
        filter_scale = 0.0

        output_img, new_anno, _ = update_image_and_anno(img_list, empty_annos, idxs, 
                                                         output_size, scale_range, filter_scale)
        assert new_anno == []
        assert isinstance(output_img, np.ndarray)
        assert output_img.shape[0] == output_size[0]
        assert output_img.shape[1] == output_size[1]

    def test_resizing_and_scaling(self):
        img_list = ['image1.jpg', 'image2.jpg', 'image3.jpg', 'image4.jpg']
        annos = [[(0, 100, 100, 200, 200)], [(1, 250, 250, 350, 350)], 
                 [(2, 100, 100, 200, 200)], [(3, 50, 50, 200, 200)]]
        idxs = [0,1,2,3]
        output_size = (720,1280)
        scale_range = (0.4, 0.6)
        filter_scale = 0.0

        _, new_anno, _ = update_image_and_anno(img_list, annos, idxs, 
                                               output_size, scale_range, filter_scale)
        for i,anno in enumerate(new_anno):
            assert isinstance(anno, tuple)
            assert len(anno) == 5
            assert anno[0] == annos[i][0][0]  # checking if id is same
            assert anno[1] >= 0.0 and anno[1] <= 1.0
            assert anno[2] >= 0.0 and anno[2] <= 1.0
            assert anno[3] >= anno[1] and anno[3] <= 1.0
            assert anno[4] >= anno[2] and anno[4] <= 1.0

    def test_different_filter_scales(self):
        img_list = ['image1.jpg', 'image2.jpg', 'image3.jpg', 'image4.jpg']
        annos = [[(0, 0.01, 0.05, 0.06, 0.1)], [(1, 0.2, 0.1, 0.25, 0.15)], 
                 [(2, 0.01, 0.05, 0.015, 0.075)], [(3, 0.01, 0.05, 0.035, 0.1)]]
        idxs = [0,1,2,3]
        filter_scale = 0.02
        output_size = (720,1280)
        scale_range = (0.4, 0.6)

        _, new_anno, _ = update_image_and_anno(img_list, annos, idxs, 
                                               output_size, scale_range, filter_scale)
        assert len(new_anno) == 2 # only 2nd and 4th annotations should remain after filter

    def test_quadrant_annotations(self):
        img_list = ['image1.jpg', 'image2.jpg', 'image3.jpg', 'image4.jpg']
        annos = [[(0, 0.1, 0.2, 0.15, 0.3)], [(1, 0.2, 0.15, 0.35, 0.4)], 
                 [(2, 0.15, 0.1, 0.35, 0.35)], [(3, 0.05, 0.05, 0.25, 0.2)]]
        idxs = [0,1,2,3]
        output_size = (720,1280)
        scale_range = (0.4, 0.6)
        filter_scale = 0.0

        _, new_anno, _ = update_image_and_anno(img_list, annos, idxs, 
                                               output_size, scale_range, filter_scale)
        for i,anno in enumerate(new_anno):
            assert anno[1] >= 0.0 and anno[1] <= 1.0 
            assert anno[2] >= 0.0 and anno[2] <= 1.0
            assert anno[3] >= anno[1] and anno[3] <= 1.0
            assert anno[4] >= anno[2] and anno[4] <= 1.0
            if i == 0:  
                assert anno[1] <= 0.6 and anno[3] <= 0.6
                assert anno[2] <= 0.6 and anno[4] <= 0.6 # for first quadrant

            if i == 1:
                assert anno[1] >= 0.4 and anno[3] >= 0.4
                assert anno[2] <= 0.6 and anno[4] <= 0.6 # for second quadrant

            if i == 2:
                assert anno[1] <= 0.6 and anno[3] <= 0.6
                assert anno[2] >= 0.4 and anno[4] >= 0.4 # for third quadrant

            if i == 3:
                assert anno[1] >= 0.4 and anno[3] >= 0.4
                assert anno[2] >= 0.4 and anno[4] >= 0.4 # for fourth quadrant

    def teardown_method(self):
        # teardown any setup objects, if required
        pass
