# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=avgpooling_8568faae41
ROOST_METHOD_SIG_HASH=avgpooling_50d65b8e1a


```
Scenario 1: Testing Average Pooling Function with Square Matrix and Valid Pooling Matrix Size and stride
Details:
  TestName: test_avgpooling_valid_input
  Description: This test verifies whether the function can correctly return the avg pooled matrix when presented with a valid square matrix, pooling size, and stride.
Execution:
  Arrange: Prepare a square numpy array with a valid size and stride.
  Act: Call the avgpooling function, passing in the prepared array, pooling size, and stride. 
  Assert: Verify the output matches the expected avg pooled matrix.
Validation:
  Ensuring the function properly handles valid input is fundamental to its correctness. This functionality aligns with the business requirement of processing average pooling on a valid 2D image.

Scenario 2: Testing Average Pooling Function with Non-Square Matrix
Details:
  TestName: test_avgpooling_non_square_matrix
  Description: This test ensures that the function throws a ValueError when presented with a non-square matrix.
Execution:
  Arrange: Prepare a non-square numpy array.
  Act: Call the avgpooling function, passing in the prepared non-square matrix, size and stride.
  Assert: Check the function raises a ValueError.
Validation:
  The test validates that the avgpooling function correctly identifies invalid non-square matrices, enforcing the business requirement that input matrices must be square.

Scenario 3: Testing Average Pooling Function with Pool Size Larger than Matrix
Details:
  TestName: test_avgpooling_large_pool_size
  Description: This test ensures the function appropriately handles a scenario where the pool size is larger than the dimensions of the square matrix.
Execution:
  Arrange: Prepare a square numpy array and a pool size larger than the array's dimensions.
  Act: Call the avgpooling function with the prepared array and pool size.
  Assert: Confirm that the function responds appropriately to this scenario.
Validation:
  This test verifies the function's ability to handle abnormal scenarios, ensuring it doesn't crash or behave unpredictably when faced with uncommon, but possible, user inputs.

Scenario 4: Testing Average Pooling function with zero stride
Details:
  TestName: test_avgpooling_zero_stride
  Description: This test ensures that the function handles a scenario where the stride is zero.
Execution:
  Arrange: Prepare a square numpy array and set the stride as zero.
  Act: Call the avgpooling function, providing the prepared array and the stride.
  Assert: Confirm that the function behaves as expected in this edge-case scenario.
Validation:
  This test helps ensure the function handles edge cases appropriately, maintaining consistency and reliability in its operation.
```

"""

# ********RoostGPT********
import pytest
import numpy as np

# Import the function to be tested
from pooling_functions import avgpooling


class Test_PoolingFunctionsAvgpooling:

    def test_avgpooling_valid_input(self):
        arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
        res = avgpooling(arr, size=2, stride=2)
        expected_res = np.array([[3., 5.], [11., 13.]])
        np.testing.assert_array_equal(res, expected_res)
        
    def test_avgpooling_non_square_matrix(self):
        with pytest.raises(ValueError):
            arr = np.array([[1,2,3],[4,5,6]])
            res = avgpooling(arr, size=2, stride=2)
        
    def test_avgpooling_large_pool_size(self):
        arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
        res = avgpooling(arr, size=5, stride=2)
        assert res.size == 0

    def test_avgpooling_zero_stride(self):
        arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
        with pytest.raises(ZeroDivisionError):
            res = avgpooling(arr, size=2, stride=0)
