# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=avgpooling_8568faae41
ROOST_METHOD_SIG_HASH=avgpooling_50d65b8e1a


```
Scenario 1: Test avgpooling function with valid square matrix
Details:
  TestName: test_avgpooling_with_valid_square_matrix
  Description: This test is to verify that the avgpooling function works correctly with a valid 2D square matrix. The function should return a 2D matrix of the average values of pool.
Execution:
  Arrange: Initialize a 2D numpy array of shape (4, 4) with integers for data testing.
  Act: Invoke the avgpooling function with the prepared 2D array, the size of pool, and stride.
  Assert: Check if the returned array by the function matches the expected averaged matrix.
Validation:
  It is essential to show the function works correctly with valid inputs and delivers the expected and correct result.

Scenario 2: Test avgpooling function with non-square matrix
Details:
  TestName: test_avgpooling_with_non_square_matrix
  Description: This test is to verify that the avgpooling function raises a ValueError when the input array is not a square matrix.
Execution:
  Arrange: Initialize a 2D numpy array of shape (3, 4) for data testing.
  Act: Invoke the avgpooling function with the prepared 2D array, the size of pool, and stride.
  Assert: Check if the function raises a ValueError.
Validation:
  It is important to check the function's ability to correctly handle violations of assumptions about the input parameters and raise appropriate exceptions.

Scenario 3: Test avgpooling function with pool size larger than matrix's shape
Details:
  TestName: test_avgpooling_with_large_pool_size
  Description: This test is to verify that the avgpooling function returns an empty array when the pool size is larger than the size of the input array.
Execution:
  Arrange: Initialize a 2D numpy array of shape (4, 4) for data testing.
  Act: Invoke the avgpooling function with the prepared 2D array, a pool size of 5, and stride.
  Assert: Check if the returned array by the function is an empty array.
Validation:
  This test validates that the function avgpooling handles corner cases correctly when the pool size is larger than the original matrix's shape, in which case it should return an empty result.

Scenario 4: Test avgpooling function with negative values in the matrix
Details:
  TestName: test_avgpooling_with_negative_values
  Description: This test is to verify that the avgpooling function handles negative values correctly in the input array.
Execution:
  Arrange: Initialize a 2D numpy array of shape (4, 4) with negative values for data testing.
  Act: Invoke the avgpooling function with the prepared 2D array, the size of pool, and stride.
  Assert: Check if the output values are correctly averaged including negative values.
Validation:
  This test ensures that the function works correctly with negative values and returns the correct average of every pooling matrix, providing that real-world data can include negative pixel values.
```
"""

# ********RoostGPT********
import numpy as np
import pytest
from pooling_functions import avgpooling

  
class Test_PoolingFunctionsAvgpooling:
  
    def test_avgpooling_with_valid_square_matrix(self):
        # Arrange
        arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
        pool_size = 2
        stride = 2
            
        # Act
        output = avgpooling(arr, pool_size, stride)
            
        # Assert
        assert np.array_equal(output, np.array([[3.5, 5.5],[11.5, 13.5]]))

    def test_avgpooling_with_non_square_matrix(self):
        # Arrange
        arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
        pool_size = 2
        stride = 2
        
        # Act and Assert
        with pytest.raises(ValueError):
            output = avgpooling(arr, pool_size, stride)

    def test_avgpooling_with_large_pool_size(self):
        # Arrange
        arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
        pool_size = 5
        stride = 2
        
        # Act
        output = avgpooling(arr, pool_size, stride)
        
        # Assert
        assert output.size == 0

    def test_avgpooling_with_negative_values(self):
        # Arrange
        arr = np.array([[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12],[-13,-14,-15,-16]])
        pool_size = 2
        stride = 2
        
        # Act
        output = avgpooling(arr, pool_size, stride)
        
        # Assert
        assert np.array_equal(output, np.array([[-3.5, -5.5],[-11.5, -13.5]]))
