# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=update_image_and_anno_f1bc3a1974
ROOST_METHOD_SIG_HASH=update_image_and_anno_e504d35fba


```
Scenario 1: Validating Image and Annotation List Update with Horizontal Flip
Details:
  TestName: test_update_image_and_anno_horizontal_flip
  Description: This test is intended to verify if the 'update_image_and_anno' function correctly flips the images horizontally as well as update the annotation lists accordingly.
Execution:
  Arrange: Prepare a list of image paths and their corresponding annotations.
  Act: Invoke the 'update_image_and_anno' function with the prepared image list, annotation list, and flip_type set to 1 (for horizontal flip).
  Assert: Check that the returned updated image list shows images that are correctly flipped horizontally and the updated annotation lists correspond to the transformations.
Validation:
  The successful pass of this test ensures 'update_image_and_anno' function correctly performs horizontal flips on images and also updates annotations properly.

Scenario 2: Validating Image and Annotation List Update with Vertical Flip
Details:
  TestName: test_update_image_and_anno_vertical_flip
  Description: This test verifies if the function correctly flips images vertically and updates annotation list accordingly when flip_type set to 0.
Execution:
  Arrange: Organize a set of image paths and their corresponding annotations.
  Act: Invoke the function 'update_image_and_anno' with the image list, annotation list, and flip_type set to 0 (for vertical flip).
  Assert: Ensure that the returned updated image list shows images that are correctly flipped vertically. Moreover, check if the transformed annotations directly correspond to the alterations.
Validation:
  The successful execution of this test certifies that 'update_image_and_anno' function properly flips images vertically and properly adjusts annotations.

Scenario 3: Ensuring Correct Path Return for Each Image
Details:
  TestName: test_update_image_and_anno_path_return
  Description: This test will check if the correct paths were returned for each of the updated image.
Execution:
  Arrange: Assemble a list of image paths along with their corresponding annotations.
  Act: Invoke the 'update_image_and_anno' function using these lists as parameters.
  Assert: Validate that the function returns the correct paths for each of the updated images.
Validation:
  An important feature of 'update_image_and_anno' function is to return correct image paths. A successful run of this test guarantees that the function maintains this crucial feature.

Scenario 4: Verifying Function's Behavior with Empty Input Lists
Details:
  TestName: test_update_image_and_anno_empty_input
  Description: This test will check whether the function correctly handles and returns expected results when both input lists for images and annotations are empty.
Execution:
  Arrange: Arrange for empty lists for images and annotations.
  Act & Assert: Call the function with these empty lists and assert that the function returns empty lists for new image list, new annotations list and path list.
Validation:
  Ensuring the correct output for empty input lists will ensure the robustness of 'update_image_and_anno' functionality even in edge cases.
```
"""

# ********RoostGPT********
import pytest
import cv2
import numpy as np
from flip_augmentation import update_image_and_anno

class Test_FlipAugmentationUpdateImageAndAnno:

    @pytest.mark.regression
    @pytest.mark.positive
    def test_update_image_and_anno_horizontal_flip(self):
        # Scenario 1: 
        # Arrange
        img_list = ["test_images/1.jpg", "test_images/2.jpg"]
        anno_list = [[(1, 0.5, 0.5, 0.2, 0.3), (2, 0.6, 0.4, 0.25, 0.3)],
                     [(1, 0.7, 0.5, 0.2, 0.3), (2, 0.8, 0.6, 0.25, 0.3)]]
        flip_type = 1

        # Act 
        new_imgs_list, new_annos_lists, _ = update_image_and_anno(img_list, anno_list, flip_type)

        # Assert
        for i in range(len(img_list)):
            img = cv2.imread(img_list[i])
            flipped_img = cv2.flip(img, flip_type)
            np.testing.assert_array_equal(new_imgs_list[i] , flipped_img)
            for n_anno, o_anno in zip(new_annos_lists[i], anno_list[i]):
                assert n_anno[0] == o_anno[0]
                assert n_anno[1] == 1 - o_anno[1]
                assert n_anno[2:] == o_anno[2:]

    @pytest.mark.regression
    @pytest.mark.positive
    def test_update_image_and_anno_vertical_flip(self):
        # Scenario 2: 
        # Arrange
        img_list = ["test_images/1.jpg", "test_images/2.jpg"]
        anno_list = [[(1, 0.5, 0.5, 0.2, 0.3), (2, 0.6, 0.4, 0.25, 0.3)],
                     [(1, 0.7, 0.5, 0.2, 0.3), (2, 0.8, 0.6, 0.25, 0.3)]]
        flip_type = 0

        # Act 
        new_imgs_list, new_annos_lists, _ = update_image_and_anno(img_list, anno_list, flip_type)

        # Assert
        for i in range(len(img_list)):
            img = cv2.imread(img_list[i])
            flipped_img = cv2.flip(img, flip_type)
            np.testing.assert_array_equal(new_imgs_list[i] , flipped_img)
            for n_anno, o_anno in zip(new_annos_lists[i], anno_list[i]):
                assert n_anno[0] == o_anno[0]
                assert n_anno[2] == 1 - o_anno[2]
                assert n_anno[1] == o_anno[1]
                assert n_anno[3:] == o_anno[3:]

    @pytest.mark.regression
    @pytest.mark.positive
    def test_update_image_and_anno_path_return(self):
        # Scenario 3: 
        # Arrange
        img_list = ["test_images/1.jpg", "test_images/2.jpg"]
        anno_list = [[(1, 0.5, 0.5, 0.2, 0.3), (2, 0.6, 0.4, 0.25, 0.3)],
                     [(1, 0.7, 0.5, 0.2, 0.3), (2, 0.8, 0.6, 0.25, 0.3)]]

        # Act 
        _, _, path_list = update_image_and_anno(img_list, anno_list)

        # Assert
        for i in range(len(img_list)):
            assert path_list[i] == img_list[i]

    @pytest.mark.regression
    @pytest.mark.negative
    def test_update_image_and_anno_empty_input(self):
        # Scenario 4:
        # Arrange
        img_list = []
        anno_list = []

        # Act - Assert
        new_imgs_list, new_annos_lists, path_list = update_image_and_anno(img_list, anno_list)
        
        assert len(new_imgs_list) == 0
        assert len(new_annos_lists) == 0
        assert len(path_list) == 0
