# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=binary_mask_4fab79a2c0
ROOST_METHOD_SIG_HASH=binary_mask_ed6e36cc93


Scenario 1: Verify Masking by an Image of Zeros:
Details:
  TestName: test_binary_mask_for_zeros
  Description: Test if all values in the false_mask is 0, when image_map is entirely composed of zeros.
Execution:
  Arrange: Create image_gray and image_map as arrays of zeros with the same shape. 
  Act: Call the binary_mask with these two arrays as input.
  Assert: Check that false_mask does not contain any value other than 0.
Validation:
  The method binary_mask replaces pixel values in false_mask with 0 where the corresponding mask pixel is 0. If all mask pixels are 0, all output pixels should also be 0, validating this part of the function's implementation. 

Scenario 2: Verify Masking by an Image of Ones:
Details:
  TestName: test_binary_mask_for_ones
  Description: Test if all values in the true_mask is 1, when image_map is entirely composed of ones.
Execution:
  Arrange: Create image_gray and image_map as arrays of ones with the same shape.
  Act: Call the binary_mask with these two arrays as input.
  Assert: Check that true_mask does not contain any value other than 1.
Validation:
  This test guarantees that the binary_mask function correctly replaces values with 1 in the true_mask where the corresponding values in image_map are 1, demonstrating the expected behavior of binary_mask itself.

Scenario 3: Check Complementarity:
Details:
  TestName: test_binary_mask_complementarity
  Description: Test that the application of the mask and its complement are mutually exclusive in terms of pixel manipulation.
Execution:
  Arrange: Generate a random 2D numpy array for image_gray and image_map. 
  Act: Call the binary_mask with these two arrays, and then check if for every pixel, only either the corresponding pixel in true_mask or false_mask has been modified.
  Assert: Check if wherever true_mask has value 1, the corresponding pixel on false_mask is not 0 and vice-versa.
Validation:
  This test checks a key aspect of the function behavior, which is the correctness of the mutual exclusivity manipulation on two separate maps. This mirrors the expected use case of the function in real-life scenarios, forming strong evidence of its correctness.

Scenario 4: Validate against Real Images:
Details:
  TestName: test_binary_mask_real_images
  Description: Confirm the correct function of binary_mask when using real world image data.
Execution:
  Arrange: Load a real grayscale image into the numpy array image_gray. Create a random binary image with shape equal to image_gray for image_map. 
  Act: Apply the function binary_mask.
  Assert: Assert whether all modifications followed the rule of binary masking. Wherever image_map was 0, check if the corresponding pixel in the false_mask is 0. Wherever image_map was 1, check if the corresponding pixel in the true_mask is 1.
Validation:
  This test validates the practical usefulness of the function by testing it in a real-world scenario and checking its correctness. This ensures that the function works properly under conditions it would presumably encounter in an actual code.
"""

# ********RoostGPT********
import pytest
import numpy as np
import imageio
from haralick_descriptors import binary_mask

class Test_HaralickDescriptorsBinaryMask:
    def test_binary_mask_for_zeros(self):
        #Arrange
        image_gray = np.zeros((10,10), dtype=np.uint8)
        image_map = np.zeros((10,10), dtype=np.uint8)
        #Act
        true_mask, false_mask = binary_mask(image_gray, image_map)
        #Assert
        assert np.all(false_mask == 0)

    def test_binary_mask_for_ones(self):
        #Arrange
        image_gray = np.ones((10,10), dtype=np.uint8)
        image_map = np.ones((10,10), dtype=np.uint8)
        #Act
        true_mask, false_mask = binary_mask(image_gray, image_map)
        #Assert
        assert np.all(true_mask == 1)

    def test_binary_mask_complementarity(self):
        #Arrange
        image_gray = np.random.randint(0, 255, (10,10), dtype=np.uint8)
        image_map = np.random.choice([0, 1], (10,10), dtype=np.uint8)
        #Act
        true_mask, false_mask = binary_mask(image_gray, image_map)
        #Assert
        assert np.all((true_mask == 1) == (false_mask != 0))

    @pytest.mark.mandatory
    def test_binary_mask_real_images(self):
        #Arrange
        image_gray = imageio.imread('test_gray_image.png')
        image_map = np.random.choice([0, 1], image_gray.shape, dtype=np.uint8)
        #Act
        true_mask, false_mask = binary_mask(image_gray, image_map)
        #Assert
        assert np.all((image_map == 1) == (true_mask == 1))
        assert np.all((image_map == 0) == (false_mask == 0))
