# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=opening_filter_bffcc54fa4
ROOST_METHOD_SIG_HASH=opening_filter_50c3034f83


Scenario 1: Opening filter applied on the binary image with default kernel
Details:
  TestName: test_opening_filter_default_kernel
  Description: This test is intended to verify the correct behavior of the opening_filter function when applied to a binary image with the default kernel, i.e., a 3x3 matrix of ones.
Execution:
  Arrange: Initialize a binary image as a ndarray.
  Act: Call the opening_filter function with the prepared binary image as the only argument.
  Assert: Check that the resulted binary image is correct according to the theory of the opening filter in digital image processing, i.e., all the bright spots (pixels with value 1) smaller than the size of the kernel are removed.
Validation:
  This test checks the correctness of the opening_filter function, according to its specifications, in a typical situation when the kernel provided is None.

Scenario 2: Opening filter applied on the binary image with a specific kernel
Details:
  TestName: test_opening_filter_specific_kernel
  Description: This test is intended to verify the correct behavior of the opening_filter function when applied to a binary image with a specific kernel.
Execution:
  Arrange: Initialize a binary image and a specific kernel as ndarrays.
  Act: Call the opening_filter function with the prepared binary image and kernel as arguments.
  Assert: Check that the resulted binary image is correct according to the theory of the opening filter in digital image processing, using the specific kernel.
Validation:
  This test checks the correctness of the opening_filter function, according to its specifications, under the condition when a specific kernel instead of the default one is employed.

Scenario 3: Opening filter applied on an empty image
Details:
  TestName: test_opening_filter_empty_image
  Description: This test is intended to verify the correct behavior of the opening_filter function when applied to an empty image.
Execution:
  Arrange: Initialize an empty image as a ndarray.
  Act: Call the opening_filter function with the empty image as the only argument.
  Assert: Check that the resulting image is also empty, as by definition, no changes can be added to an empty image.
Validation:
  This test checks the robustness of the opening_filter function, making sure it can deal with edge cases like empty input.

"""

# ********RoostGPT********
import pytest
import imageio.v2 as imageio
import numpy as np
from haralick_descriptors import opening_filter

@pytest.mark.parametrize(
    "image, expected",
    [
        ([[
            [1,1,1,0,0],
            [1,0,0,0,1],
            [1,0,0,0,1],
            [1,1,1,1,1],
            [0,0,0,0,0]
        ]], [[
            [1,1,1,0,0],
            [1,0,0,0,0],
            [1,0,0,0,0],
            [1,1,1,1,1],
            [0,0,0,0,0]
        ]])
    ]
)
def test_opening_filter_default_kernel(image, expected):
    image = np.array(image, dtype=np.uint8)
    expected = np.array(expected, dtype=np.uint8)

    result = opening_filter(image)

    np.testing.assert_array_almost_equal(result, expected)


@pytest.mark.parametrize(
    "image, kernel, expected",
    [
        ([[
            [1,1,1,0,0],
            [1,0,0,0,1],
            [1,0,0,0,1],
            [1,1,1,1,1],
            [0,0,0,0,0]
        ]], [[1,1], [1,1]], [[
            [1,1,1,0,0],
            [1,1,1,1,1],
            [1,1,0,1,1],
            [1,1,1,1,1],
            [0,0,0,0,0]
        ]])
    ]
)
def test_opening_filter_specific_kernel(image, kernel, expected):
    image = np.array(image, dtype=np.uint8)
    kernel = np.array(kernel, dtype=np.uint8)
    expected = np.array(expected, dtype=np.uint8)

    result = opening_filter(image, kernel)

    np.testing.assert_array_almost_equal(result, expected)


@pytest.mark.parametrize(
    "image, expected",
    [
        ([[]], [[]])
    ]
)
def test_opening_filter_empty_image(image, expected):
    image = np.array(image, dtype=np.uint8)
    expected = np.array(expected, dtype=np.uint8)

    result = opening_filter(image)

    np.testing.assert_array_almost_equal(result, expected)
