# Consolidated test file for pooling_functions.py
# Generated by Roost
import numpy as np
from PIL import Image
from doctest import testmod


# Content from: test_PoolingFunctionsMaxpooling.py
# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=maxpooling_f4c12bf153
ROOST_METHOD_SIG_HASH=maxpooling_4f9b1c141c


 1: Basic Maxpooling Scenario
Details:
  TestName: test_basic_maxpooling
  Description: This test verifies that the maxpooling function correctly performs maxpooling on a standard 4x4 matrix with a pooling size of 2 and stride of 2.
Execution:
  Arrange: Prepare a 4x4 matrix and set size to 2 and stride to 2.
  Act: Call maxpooling(arr, 2, 2).
  Assert: The result should be [[6., 8.],[14., 16.]].
Validation:
  This test ensures the function correctly handles the basic case specified in the docstring and confirms the pooling mechanism.

"""

# ********RoostGPT********
import pytest
import numpy as np
from pooling_functions import maxpooling

class Test_PoolingFunctionsMaxpooling:
    @pytest.mark.smoke
    @pytest.mark.valid
    @pytest.mark.positive
    def test_basic_maxpooling(self):
        # Arrange
        arr = np.array([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12],
                         [13, 14, 15, 16]])
        size = 2
        stride = 2
        expected_output = np.array([[6., 8.],
                                     [14., 16.]])

        # Act
        result = maxpooling(arr, size, stride)

        # Assert
        np.testing.assert_array_equal(result, expected_output)

    @pytest.mark.valid
    @pytest.mark.positive
    def test_maxpooling_different_input(self):
        # Arrange
        arr = np.array([[147, 180, 122],
                         [241, 76, 32],
                         [126, 13, 157]])
        size = 2
        stride = 1
        expected_output = np.array([[241., 180.],
                                     [241., 157.]])

        # Act
        result = maxpooling(arr, size, stride)

        # Assert
        np.testing.assert_array_equal(result, expected_output)

    @pytest.mark.invalid
    @pytest.mark.negative
    def test_maxpooling_non_square_matrix(self):
        # Arrange
        arr = np.array([[1, 2, 3],
                         [4, 5, 6]])
        size = 2
        stride = 2

        # Act & Assert
        with pytest.raises(ValueError, match="The input array is not a square matrix"):
            maxpooling(arr, size, stride)

    @pytest.mark.valid
    @pytest.mark.positive
    def test_maxpooling_large_matrix(self):
        # Arrange
        arr = np.random.randint(0, 255, (100, 100))
        size = 2
        stride = 2

        # Act
        result = maxpooling(arr, size, stride)

        # Assert
        assert result.shape == (49, 49)

    @pytest.mark.valid
    @pytest.mark.positive
    def test_maxpooling_edge_case(self):
        # Arrange
        arr = np.array([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12],
                         [13, 14, 15, 16]])
        size = 4
        stride = 4
        expected_output = np.array([[16.]])

        # Act
        result = maxpooling(arr, size, stride)

        # Assert
        np.testing.assert_array_equal(result, expected_output)

# Content from: test_PoolingFunctionsAvgpooling.py
# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=avgpooling_8568faae41
ROOST_METHOD_SIG_HASH=avgpooling_50d65b8e1a


 1: Basic Valid Input
Details:
  TestName: test_avgpooling_basic_valid_input
  Description: This test verifies that the avgpooling function correctly processes a valid square matrix with specified size and stride.
Execution:
  Arrange: No specific setup required. The input matrix and parameters are predefined.
  Act: Call avgpooling with input matrix [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]], size 2, and stride 2.
  Assert: The output should be [[3.0, 5.0], [11.0, 13.0]].
Validation:
  This test confirms that the function correctly computes the average pooling for a basic valid input, ensuring that the core logic is functioning as expected.


"""

# ********RoostGPT********
import pytest
import numpy as np
from pooling_functions import avgpooling

class Test_PoolingFunctionsAvgpooling:

    @pytest.mark.valid
    def test_avgpooling_basic_valid_input(self):
        input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
        size = 2
        stride = 2
        expected_output = np.array([[3.0, 5.0], [11.0, 13.0]])
        result = avgpooling(input_matrix, size, stride)
        assert np.array_equal(result, expected_output)

    @pytest.mark.valid
    def test_avgpooling_valid_input_odd_size(self):
        input_matrix = np.array([[147, 180, 122], [241, 76, 32], [126, 13, 157]])
        size = 2
        stride = 1
        expected_output = np.array([[161.0, 102.0], [114.0, 69.0]])
        result = avgpooling(input_matrix, size, stride)
        assert np.array_equal(result, expected_output)

    @pytest.mark.invalid
    def test_avgpooling_non_square_matrix(self):
        input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
        size = 2
        stride = 2
        with pytest.raises(ValueError):
            avgpooling(input_matrix, size, stride)

    @pytest.mark.invalid
    def test_avgpooling_size_greater_than_matrix(self):
        input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
        size = 5
        stride = 2
        expected_output = np.array([])
        result = avgpooling(input_matrix, size, stride)
        assert np.array_equal(result, expected_output)

    @pytest.mark.valid
    def test_avgpooling_stride_greater_than_size(self):
        input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
        size = 2
        stride = 3
        expected_output = np.array([[3.0], [11.0]])
        result = avgpooling(input_matrix, size, stride)
        assert np.array_equal(result, expected_output)

    @pytest.mark.valid
    def test_avgpooling_large_matrix(self):
        input_matrix = np.random.rand(100, 100)
        size = 10
        stride = 5
        expected_output = np.zeros(((100 - size) // stride + 1, (100 - size) // stride + 1))
        for i in range(expected_output.shape[0]):
            for j in range(expected_output.shape[1]):
                expected_output[i, j] = int(np.average(input_matrix[i * stride:i * stride + size, j * stride:j * stride + size]))
        result = avgpooling(input_matrix, size, stride)
        assert np.array_equal(result, expected_output)

if __name__ == '__main__':
    pytest.main()
