# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=normalize_array_9e76dac53d
ROOST_METHOD_SIG_HASH=normalize_array_26a5e833a8


Scenario 1: Test Normal Data Normalization
Details:
  TestName: test_normalize_array_positive_integers
  Description: This test is intended to evaluate the normalization for a range of positive integers between 0 to cap.
Execution:
  Arrange: Initialize a numpy array with positive integers.
  Act: Call normalize_array on the array with a specified cap value.
  Assert: Expected output is to validate that the return array values are within the cap specified and comparing the fractional value of each number to what is expected.
Validation:
  This test is crucial to validate that the normal data-case works expectedly and normalize_array function handles standard inputs correctly.

Scenario 2: Test Single Unique Value Array
Details:
  TestName: test_normalize_array_single_unique_value
  Description: This test is for checking the scenario when all values in the array are the same.
Execution:
  Arrange: Initialize an array with same valued elements.
  Act: Invoke normalize_array on the array.
  Assert: Check if the returned array has all the elements as zero.
Validation:
  These kind of tests validate the edge-case where the minimum and maximum values in the array are the same, which checks the handling of division by zero scenario.

Scenario 3: Test Negative Value Normalization
Details:
  TestName: test_normalize_array_negative_values
  Description: This test is to verify the normalization of negative number arrays ranging in 0 to cap.
Execution:
  Arrange: Initialize a numpy array having negative integer numbers.
  Act: Call normalize_array function on this array.
  Assert: The return array values should be in within 0 to cap range and compared to the expected output.
Validation:
  This scenario helps in validating the function's behavior with negative numbers, ensuring that negative inputs don't disrupt normalization process.

Scenario 4: Test Empty Array Normalization
Details:
  TestName: test_normalize_array_empty_array
  Description: This test is intended to verify the handling of an empty numpy array.
Execution:
  Arrange: A numpy array of zero length is created.
  Act: Call normalize_array function with this array.
  Assert: The returned array is also expected to be of zero length.
Validation:
  Such tests are important to verify that the provided function can handle empty inputs without error.

Scenario 5: Test Array with Zero Values Normalization
Details:
  TestName: test_normalize_array_zero_values
  Description: The test is meant to verify normalization process of an numpy array containing zeros.
Execution:
  Arrange: Initialize an array with zero elements.
  Act: Invoke normalize_array function on this array.
  Assert: Check if the returned array has all the elements as zero.
Validation:
  This scenario is important for validating normalization for zero valued arrays, it checks the capability of function for not introducing any non-zero values during normalization.
"""

# ********RoostGPT********
import pytest
import numpy as np
from haralick_descriptors import normalize_array

class Test_HaralickDescriptorsNormalizeArray:
    @pytest.mark.positive
    def test_normalize_array_positive_integers(self):
        array = np.array([2, 3, 5, 7])
        cap = 1.0
        normalized_array = normalize_array(array, cap)
        expected_array = np.array([0. , 0.2, 0.6, 1. ])
        assert np.array_equal(normalized_array, expected_array), "Normalization of positive values is incorrect."

    @pytest.mark.edge
    def test_normalize_array_single_unique_value(self):
        array = np.array([5, 5, 5, 5])
        normalized_array = normalize_array(array)
        expected_array = np.array([0., 0., 0., 0.])
        assert np.array_equal(normalized_array, expected_array), "Normalization of array with single unique value is incorrect."

    @pytest.mark.negative
    def test_normalize_array_negative_values(self):
        array = np.array([-2, -3, -5, -7])
        cap = 1.0
        normalized_array = normalize_array(array, cap)
        expected_array = np.array([1., 0.8, 0.4, 0.])
        assert np.array_equal(normalized_array, expected_array), "Normalization of negative values is incorrect."

    @pytest.mark.edge
    def test_normalize_array_empty_array(self):
        array = np.array([])
        normalized_array = normalize_array(array)
        assert len(normalized_array) == 0, "Normalization of empty array is incorrect."

    @pytest.mark.edge
    def test_normalize_array_zero_values(self):
        array = np.array([0, 0, 0, 0])
        normalized_array = normalize_array(array)
        expected_array = np.array([0., 0., 0., 0.])
        assert np.array_equal(normalized_array, expected_array), "Normalization of zero values is incorrect."
