# Consolidated test file for pooling_functions.py
# Generated by Roost
import numpy as np
from PIL import Image
from doctest import testmod


# Content from: test_PoolingFunctionsMaxpooling.py
# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=maxpooling_f4c12bf153
ROOST_METHOD_SIG_HASH=maxpooling_4f9b1c141c


 1: Basic Maxpooling Operation
Details:
  TestName: test_basic_maxpooling
  Description: Verifies the basic functionality of maxpooling by testing with a simple 4x4 matrix.
Execution:
  Arrange: Initialize a simple 4x4 matrix and set size and stride.
  Act: Call maxpooling with the initialized matrix, size=2, and stride=2.
  Assert: Ensure the output is the expected 2x2 maxpooled matrix.
Validation:
  Rationalize that this test validates the core pooling mechanism with typical input values.

Scenario 2: Maxpooling with Different Size and Stride
Details:
  TestName: test_different_size_and_stride
  Description: Tests maxpooling with a different size and stride to ensure flexibility.
Execution:
  Arrange: Initialize a 4x4 matrix and set size=3 and stride=1.
  Act: Call maxpooling with the initialized matrix, size=3, and stride=1.
  Assert: Ensure the output is a valid maxpooled matrix considering the new size and stride.
Validation:
  Rationalize that this test checks the function's ability to handle different pooling windows and strides.

Scenario 3: Maxpooling with Non-Square Matrix
Details:
  TestName: test_non_square_matrix
  Description: Verifies the function raises an error when the input is not a square matrix.
Execution:
  Arrange: Initialize a non-square matrix.
  Act: Call maxpooling with the non-square matrix.
  Assert: Ensure a ValueError is raised.
Validation:
  Rationalize that this test confirms the function's validation of input shape.

Scenario 4: Maxpooling with Larger Matrix
Details:
  TestName: test_larger_matrix
  Description: Tests maxpooling with a larger matrix to ensure performance and correctness.
Execution:
  Arrange: Initialize a larger square matrix (e.g., 10x10).
  Act: Call maxpooling with the larger matrix, size=2, and stride=2.
  Assert: Ensure the output is the expected maxpooled matrix.
Validation:
  Rationalize that this test verifies the function's scalability and correctness with larger matrices.

Scenario 5: Maxpooling with Overlapping Windows
Details:
  TestName: test_overlapping_windows
  Description: Tests maxpooling with overlapping pooling windows to ensure correct handling.
Execution:
  Arrange: Initialize a 5x5 matrix and set size=3 and stride=1.
  Act: Call maxpooling with the initialized matrix, size=3, and stride=1.
  Assert: Ensure the output is the expected maxpooled matrix with overlapping pooling windows.
Validation:
  Rationalize that this test checks the function's ability to handle overlapping pooling windows.

Scenario 6: Maxpooling with Single Element Matrix
Details:
  TestName: test_single_element_matrix
  Description: Tests maxpooling with a single element matrix to ensure edge case handling.
Execution:
  Arrange: Initialize a 1x1 matrix.
  Act: Call maxpooling with the 1x1 matrix, size=1, and stride=1.
  Assert: Ensure the output is the same 1x1 matrix.
Validation:
  Rationalize that this test verifies the function's behavior with the smallest possible input.

Scenario 7: Maxpooling with Large Stride
Details:
  TestName: test_large_stride
  Description: Tests maxpooling with a stride larger than the pooling size to ensure correct handling.
Execution:
  Arrange: Initialize a 4x4 matrix and set size=2 and stride=3.
  Act: Call maxpooling with the initialized matrix, size=2, and stride=3.
  Assert: Ensure the output is the expected maxpooled matrix with a large stride.
Validation:
  Rationalize that this test checks the function's ability to handle large strides relative to the pooling size.

Scenario 8: Maxpooling with Edge Cases
Details:
  TestName: test_edge_cases
  Description: Tests maxpooling with edge cases such as very small or very large input values.
Execution:
  Arrange: Initialize matrices with very small and very large values.
  Act: Call maxpooling with the matrices.
  Assert: Ensure the output is the expected maxpooled matrix.
Validation:
  Rationalize that this test verifies the function's correctness with extreme input values.

"""

# ********RoostGPT********
import pytest
import numpy as np
from pooling_functions import maxpooling

class Test_PoolingFunctionsMaxpooling:

    @pytest.mark.smoke
    @pytest.mark.valid
    def test_basic_maxpooling(self):
        # Arrange
        input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
        size = 2
        stride = 2
        expected_output = np.array([[6, 8], [14, 16]])

        # Act
        output = maxpooling(input_matrix, size, stride)

        # Assert
        np.testing.assert_array_equal(output, expected_output)

    @pytest.mark.valid
    def test_different_size_and_stride(self):
        # Arrange
        input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
        size = 3
        stride = 1
        expected_output = np.array([[11, 12], [15, 16]])

        # Act
        output = maxpooling(input_matrix, size, stride)

        # Assert
        np.testing.assert_array_equal(output, expected_output)

    @pytest.mark.invalid
    def test_non_square_matrix(self):
        # Arrange
        input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

        # Act & Assert
        with pytest.raises(ValueError):
            maxpooling(input_matrix, 2, 2)

    @pytest.mark.valid
    def test_larger_matrix(self):
        # Arrange
        input_matrix = np.random.randint(0, 100, (10, 10))
        size = 2
        stride = 2

        # Act
        output = maxpooling(input_matrix, size, stride)

        # Assert
        assert output.shape == ((input_matrix.shape[0] - size) // stride + 1, (input_matrix.shape[1] - size) // stride + 1)

    @pytest.mark.valid
    def test_overlapping_windows(self):
        # Arrange
        input_matrix = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
        size = 3
        stride = 1
        expected_output = np.array([[13, 14, 15], [18, 19, 20], [23, 24, 25]])

        # Act
        output = maxpooling(input_matrix, size, stride)

        # Assert
        np.testing.assert_array_equal(output, expected_output)

    @pytest.mark.valid
    def test_single_element_matrix(self):
        # Arrange
        input_matrix = np.array([[42]])
        size = 1
        stride = 1
        expected_output = np.array([[42]])

        # Act
        output = maxpooling(input_matrix, size, stride)

        # Assert
        np.testing.assert_array_equal(output, expected_output)

    @pytest.mark.valid
    def test_large_stride(self):
        # Arrange
        input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
        size = 2
        stride = 3
        expected_output = np.array([[6]])

        # Act
        output = maxpooling(input_matrix, size, stride)

        # Assert
        np.testing.assert_array_equal(output, expected_output)

    @pytest.mark.valid
    def test_edge_cases(self):
        # Arrange
        input_matrix_very_small = np.array([[1, 1], [1, 1]])
        input_matrix_very_large = np.array([[1e6, 2e6], [3e6, 4e6]])
        size = 2
        stride = 2

        # Act
        output_very_small = maxpooling(input_matrix_very_small, size, stride)
        output_very_large = maxpooling(input_matrix_very_large, size, stride)

        # Assert
        np.testing.assert_array_equal(output_very_small, np.array([[1]]))
        np.testing.assert_array_equal(output_very_large, np.array([[4e6]]))

# Content from: test_PoolingFunctionsAvgpooling.py
# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=avgpooling_8568faae41
ROOST_METHOD_SIG_HASH=avgpooling_50d65b8e1a


 1: Valid AvgPooling on Square Matrix with Size 2 and Stride 2
Details:
  TestName: test_avgpooling_valid_case
  Description: Verify that the avgpooling function correctly computes the average pooling on a valid square matrix with pooling size 2 and stride 2.
Execution:
  Arrange: Initialize a square matrix of size 4x4.
  Act: Call avgpooling with the initialized matrix, size=2, and stride=2.
  Assert: Check if the output is as expected, i.e., [[3, 5], [11, 13]].
Validation:
  Rationalize the importance of this test by ensuring that the function correctly performs average pooling on a typical scenario, validating the core functionality of the function.

Scenario 2: Valid AvgPooling on Square Matrix with Size 2 and Stride 1
Details:
  TestName: test_avgpooling_stride_1
  Description: Verify that the avgpooling function correctly computes the average pooling on a square matrix with pooling size 2 and stride 1.
Execution:
  Arrange: Initialize a square matrix of size 3x3.
  Act: Call avgpooling with the initialized matrix, size=2, and stride=1.
  Assert: Check if the output is as expected, i.e., [[161, 102], [114, 69]].
Validation:
  Rationalize the importance of this test by ensuring that the function correctly handles different strides and validates the stride parameter functionality.

Scenario 3: Non-Square Matrix Input
Details:
  TestName: test_avgpooling_non_square_matrix
  Description: Verify that the avgpooling function raises a ValueError when the input matrix is not a square matrix.
Execution:
  Arrange: Initialize a non-square matrix.
  Act: Call avgpooling with the initialized matrix, size=2, and stride=2.
  Assert: Check if a ValueError is raised.
Validation:
  Rationalize the importance of this test by ensuring that the function correctly handles invalid input scenarios and maintains data integrity.

Scenario 4: Pooling Size Larger than Matrix Dimensions
Details:
  TestName: test_avgpooling_large_pooling_size
  Description: Verify that the avgpooling function handles cases where the pooling size is larger than the matrix dimensions gracefully.
Execution:
  Arrange: Initialize a small square matrix.
  Act: Call avgpooling with the initialized matrix, size=3, and stride=1.
  Assert: Check if the function returns an empty matrix or handles it appropriately, depending on the function's design.
Validation:
  Rationalize the importance of this test by ensuring that the function can gracefully handle edge cases where the pooling size exceeds the matrix dimensions.

Scenario 5: Large Matrix with Various Strides
Details:
  TestName: test_avgpooling_large_matrix
  Description: Verify that the avgpooling function correctly computes the average pooling on a large square matrix with various strides.
Execution:
  Arrange: Initialize a large square matrix (e.g., 10x10).
  Act: Call avgpooling with the initialized matrix, size=3, and varying strides (e.g., stride=1, stride=2).
  Assert: Check if the output is as expected for each stride value.
Validation:
  Rationalize the importance of this test by ensuring that the function scales well with larger matrices and various stride values, validating performance and correctness.

Scenario 6: Edge Case with Minimum Matrix Size and Pooling
Details:
  TestName: test_avgpooling_minimum_size
  Description: Verify that the avgpooling function correctly handles the edge case with the minimum matrix size and pooling size.
Execution:
  Arrange: Initialize a 2x2 matrix.
  Act: Call avgpooling with the initialized matrix, size=2, and stride=1.
  Assert: Check if the function returns the correct average value or handles it appropriately.
Validation:
  Rationalize the importance of this test by ensuring that the function correctly handles the smallest possible input scenario, validating edge case handling.

Scenario 7: Overlapping Pooling Windows
Details:
  TestName: test_avgpooling_overlapping_windows
  Description: Verify that the avgpooling function correctly computes the average pooling with overlapping windows.
Execution:
  Arrange: Initialize a square matrix.
  Act: Call avgpooling with the initialized matrix, size=2, and stride=1.
  Assert: Check if the output is as expected, considering the overlapping windows.
Validation:
  Rationalize the importance of this test by ensuring that the function correctly handles overlapping pooling windows, validating the stride parameter functionality.

Scenario 8: Pooling Size Equal to Matrix Size
Details:
  TestName: test_avgpooling_pooling_size_equal_matrix
  Description: Verify that the avgpooling function correctly handles the scenario where the pooling size is equal to the matrix size.
Execution:
  Arrange: Initialize a square matrix.
  Act: Call avgpooling with the initialized matrix, size equal to the matrix size, and stride=1.
  Assert: Check if the function returns the correct average value.
Validation:
  Rationalize the importance of this test by ensuring that the function correctly handles the scenario where pooling size is equal to the matrix size, validating edge case handling.

"""

# ********RoostGPT********
import pytest
import numpy as np
from pooling_functions import avgpooling

class Test_PoolingFunctionsAvgpooling:

    @pytest.mark.valid
    def test_avgpooling_valid_case(self):
        # Arrange
        input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
        expected_output = np.array([[3, 5], [11, 13]])

        # Act
        result = avgpooling(input_matrix, size=2, stride=2)

        # Assert
        np.testing.assert_array_equal(result, expected_output)

    @pytest.mark.valid
    def test_avgpooling_stride_1(self):
        # Arrange
        input_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        expected_output = np.array([[5, 6], [7, 8]])

        # Act
        result = avgpooling(input_matrix, size=2, stride=1)

        # Assert
        np.testing.assert_array_equal(result, expected_output)

    @pytest.mark.invalid
    def test_avgpooling_non_square_matrix(self):
        # Arrange
        input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

        # Act & Assert
        with pytest.raises(ValueError, match="The input array is not a square matrix"):
            avgpooling(input_matrix, size=2, stride=2)

    @pytest.mark.edge
    def test_avgpooling_large_pooling_size(self):
        # Arrange
        input_matrix = np.array([[1, 2], [3, 4]])
        expected_output = np.array([[]])

        # Act
        result = avgpooling(input_matrix, size=3, stride=1)

        # Assert
        np.testing.assert_array_equal(result, expected_output)

    @pytest.mark.valid
    def test_avgpooling_large_matrix(self):
        # Arrange
        input_matrix = np.random.randint(0, 256, (10, 10))
        expected_output_stride_1 = avgpooling(input_matrix, size=3, stride=1)
        expected_output_stride_2 = avgpooling(input_matrix, size=3, stride=2)

        # Act
        result_stride_1 = avgpooling(input_matrix, size=3, stride=1)
        result_stride_2 = avgpooling(input_matrix, size=3, stride=2)

        # Assert
        np.testing.assert_array_equal(result_stride_1, expected_output_stride_1)
        np.testing.assert_array_equal(result_stride_2, expected_output_stride_2)

    @pytest.mark.edge
    def test_avgpooling_minimum_size(self):
        # Arrange
        input_matrix = np.array([[1, 2], [3, 4]])
        expected_output = np.array([[2.5]])

        # Act
        result = avgpooling(input_matrix, size=2, stride=1)

        # Assert
        np.testing.assert_array_equal(result, expected_output)

    @pytest.mark.valid
    def test_avgpooling_overlapping_windows(self):
        # Arrange
        input_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        expected_output = np.array([[5, 6], [7, 8]])

        # Act
        result = avgpooling(input_matrix, size=2, stride=1)

        # Assert
        np.testing.assert_array_equal(result, expected_output)

    @pytest.mark.edge
    def test_avgpooling_pooling_size_equal_matrix(self):
        # Arrange
        input_matrix = np.array([[1, 2], [3, 4]])
        expected_output = np.array([[2.5]])

        # Act
        result = avgpooling(input_matrix, size=2, stride=2)

        # Assert
        np.testing.assert_array_equal(result, expected_output)
