# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=get_dataset_fd4f3dcae8
ROOST_METHOD_SIG_HASH=get_dataset_b2a4fcf575


```
Scenario 1: Validating the successful execution of the function with correct input directories
Details:
  TestName: test_get_dataset_valid_input
  Description: This test is intended to verify the successful execution of the function when proper input directories for labels and images are provided.
Execution:
  Arrange: Set-up valid paths for label_dir and img_dir. Make sure these directories contain relevant files.
  Act: Invoke the get_dataset function with these directories as parameters.
  Assert: Verify that the result is two lists - one containing image paths and the other containing corresponding labels.
Validation:
  This test is essential to ensure that the function is correctly generating lists of image paths and labels from given directories. If this functionality fails, the function won't meet its business requirement.

Scenario 2: Handling unknown or invalid directory paths as input
Details:
  TestName: test_get_dataset_unknown_path
  Description: This test is intended to verify the function's behavior when unknown or invalid directories are given as input.
Execution:
  Arrange: Prepare unknown or invalid directories for both label_dir and img_dir.
  Act: Invoke the get_dataset function with these directories as parameters.
  Assert: The function should return empty lists for both image paths and labels.
Validation:
  This test verifies the robustness of the function when handling unknown or invalid inputs. This is important so that the function can correctly handle erroneous or non-existent paths without halting execution.

Scenario 3: Checking the function's ability to ignore files without label boxes
Details:
  TestName: test_get_dataset_ignores_no_label_files
  Description: This test is intended to check that the function correctly ignores image files that have no corresponding label box and doesn't include them in the return lists.
Execution:
  Arrange: Set up a scenario where an image file has no corresponding label box text file.
  Act: Invoke the get_dataset function.
  Assert: Confirm that the image file without label information is not included in the returned image and label lists.
Validation:
  This test is significant to confirm the function's accuracy and integrity in its output, ensuring only images with correct label information are included in the data.

Scenario 4: Confirming the consistency of image and label order in return lists 
Details:
  TestName: test_get_dataset_consistent_order
  Description: This test will confirm that the function consistently correlates the correct image paths with their corresponding labels in the order they appear in the returned lists.
Execution:
  Arrange: Prepare a set of label and image directories with known and consistent order of files.
  Act: Invoke the get_dataset function with these directories.
  Assert: Check that the returned lists match the known order of files and their labels.
Validation:
  This test is crucial to ensuring that the function correctly correlates and preserves the order of image files and their corresponding labels, which is vital for downstream applications that rely on this data.
```

"""

# ********RoostGPT********
import os
import glob
from flip_augmentation import get_dataset
import pytest
import cv2
import random
from string import ascii_lowercase, digits


class Test_FlipAugmentationGetDataset:

    def prepare_data(self, label_dir, img_dir):
        for i in range(10):
            img_name = ''.join(random.choices(ascii_lowercase + digits, k=5))
            cv2.imwrite(os.path.join(img_dir, f"{img_name}.jpg"), cv2.createImage([100, 100, 3], cv2.IPL_DEPTH_8U, 3))
            with open(os.path.join(label_dir, f"{img_name}.txt"), "w") as f:
                f.write("1 0.5 0.5 0.5 0.5\n")

    @pytest.mark.parametrize("label_dir,img_dir", [(r'./test_labels', r'./test_imgs')])
    def test_get_dataset_valid_input(self, label_dir, img_dir):
        self.prepare_data(label_dir, img_dir)
        img_paths, labels = get_dataset(label_dir, img_dir)
        assert len(img_paths) == len(labels) == 10
        for img_path in img_paths:
            assert os.path.exists(img_path)

    @pytest.mark.parametrize("label_dir,img_dir", [(r'./unknown_labels', r'./unknown_imgs')])
    def test_get_dataset_unknown_path(self, label_dir, img_dir):
        img_paths, labels = get_dataset(label_dir, img_dir)
        assert len(img_paths) == len(labels) == 0

    def test_get_dataset_ignores_no_label_files(self):
        label_dir = r'./test_labels_ignore'
        img_dir = r'./test_imgs_ignore'
        self.prepare_data(label_dir, img_dir)
        os.remove(os.path.join(label_dir, os.listdir(label_dir)[0]))
        img_paths, labels = get_dataset(label_dir, img_dir)
        assert len(img_paths) == len(labels) == 9
        for img_path in img_paths:
            assert os.path.exists(img_path)

    def test_get_dataset_consistent_order(self):
        label_dir = r'./test_labels_order'
        img_dir = r'./test_imgs_order'
        self.prepare_data(label_dir, img_dir)
        img_paths, labels = get_dataset(label_dir, img_dir)
        assert len(img_paths) == len(labels) == 10
        for i in range(10):
            assert img_paths[i].split('/')[-1].split('.')[0] == ' '.join(map(str, labels[i][0]))
