# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=get_distances_17a6331485
ROOST_METHOD_SIG_HASH=get_distances_166a6e990d


```
Scenario 1: Comparing all descriptors with the base descriptor
Details:
  TestName: test_get_distances_validation
  Description: This test verifies that the get_distances function correctly computes Euclidean distances among all Haralick descriptors and the base descriptor.
Execution:
  Arrange: Initialize a list of descriptors and a base integer.
  Act: Pass the descriptors and the base integer into the get_distances function.
  Assert: Check that the function returns a list of tuples with the descriptor index and the corresponding distance.
Validation:
  This test validates the core functionality of get_distances, hence it's crucial to ensure that the function processes the descriptors accurately and handles mathematical computations correctly.

Scenario 2: Check functionality with the minimum and maximum base index value
Details:
  TestName: test_get_distances_extreme_indices
  Description: This test is designed to verify that the function handles edge cases where the base index is the maximum or minimum possible value.
Execution:
  Arrange: Initialize a list of descriptors. Use the indices 0 and the length of the descriptor array minus one as the base.
  Act: Pass the descriptors and both base indices into the get_distances function.
  Assert: Check that the function returns correctly ordered Euclidean distances for each base index.
Validation:
  The test is crucial in ensuring that the boundaries for base indices are not causing issues or errors, and verifying that the function behaves as expected under the full range of possible inputs.

Scenario 3: Validate a sorted output in descending order
Details:
  TestName: test_dist_output_order
  Description: This test confirms whether the function returns distances between descriptors in decreasing order.
Execution:
  Arrange: Define a list of descriptors and a base integer.
  Act: Run the get_distances function with these input parameters.
  Assert: Check that the function's output is a list sorted in descending order.
Validation:
  This test ensures the correctness of the order of the output and reflects if the output is presented in decreasing order as specified in the function description.

Scenario 4: Verification of the Normalization range
Details:
  TestName: test_norm_range
  Description: This test checks that the function correctly normalizes distances between 0 and 1.
Execution:
  Arrange: Create a descriptor and base value.
  Act: Call the get_distances function with these inputs.
  Assert: Confirm that all returned distances are within the range [0,1].
Validation:
  This test is essential because it verifies the function's ability to correctly normalize distances, which is a critical part of its requirement specifications.
```

"""

# ********RoostGPT********
import pytest
import numpy as np
import imageio.v2 as imageio
from haralick_descriptors import get_distances

class Test_HaralickDescriptorsGetDistances:

    @pytest.mark.regression
    def test_get_distances_validation(self):
        # Arrange
        descriptors = [np.array([108, 201, 72]), np.array([255, 11, 127]), np.array([56, 56, 56]), np.array([128, 255, 107])]
        base = 1

        # Act
        result = get_distances(descriptors, base)

        # Assert
        assert isinstance(result, list)
        assert all(isinstance(item, tuple) for item in result)
        assert all(isinstance(item[0], int) and isinstance(item[1], float) for item in result)

    @pytest.mark.regression
    def test_get_distances_extreme_indices(self):
        # Arrange
        descriptors = [np.array([108, 201, 72]), np.array([255, 11, 127]), np.array([56, 56, 56]), np.array([128, 255, 107])]
        base_min = 0
        base_max = len(descriptors) - 1

        # Act
        result_min = get_distances(descriptors, base_min)
        result_max = get_distances(descriptors, base_max)

        # Assert
        assert result_min[0][0] == base_min
        assert result_max[0][0] == base_max

    @pytest.mark.regression
    def test_dist_output_order(self):
        # Arrange
        descriptors = [np.array([108, 201, 72]), np.array([255, 11, 127]), np.array([56, 56, 56]), np.array([128, 255, 107])]
        base = 1

        # Act
        result = get_distances(descriptors, base)

        # Assert
        assert all(result[i][1] >= result[i + 1][1] for i in range(len(result)-1))

    @pytest.mark.regression
    def test_norm_range(self):
        # Arrange
        descriptors = [np.array([108, 201, 72]), np.array([255, 11, 127]), np.array([56, 56, 56]), np.array([128, 255, 107])]
        base = 1

        # Act
        result = get_distances(descriptors, base)

        # Assert
        assert all(0 <= item[1] <= 1 for item in result)
