# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=get_dataset_fd4f3dcae8
ROOST_METHOD_SIG_HASH=get_dataset_b2a4fcf575


Scenario 1: Verifying Correct File Parsing and Dataset Creation by the Function
Details:
  TestName: test_FileParsingAndDatasetCreation  
  Description: This test is intended to verify the accurate parsing of label files and creation of image paths and label data sets.
Execution:
  Arrange: Create a set of dummy .txt files that mimic the label files and a set of corresponding dummy image files. 
  Act: The function is invoked with the directory of dummy label files and image files as parameters.
  Assert: Check if the function accurately produces lists of image paths and labels as per the content in dummy files.
Validation:
  This test simulates normal operation of the function. The expected result validates that the function correctly parses label files and accurately assigns labels and images' path accordingly.

Scenario 2: Verifying Handling of Nonexistent Directories
Details:
  TestName: test_NonexistentDirectories 
  Description: This test is intended to verify the function's behavior when provided with directories that do not exist.
Execution:
  Arrange: No arrangement of dummy files is required.
  Act: Call the function with directory parameters that do not exist.
  Assert: Ensure that the function returns empty lists for both 'img_paths' and 'labels'.
Validation:
  This test is important because it simulates a situation where the function is provided with invalid directory parameters. It will validate that function can correctly handle this scenario without causing errors or exceptions, and it returns correct output as per its definition.

Scenario 3: Verifying the Handling of Empty Directories 
Details:
  TestName: test_EmptyDirectories  
  Description: This test is designed to verify how the function behaves when provided with empty directories.
Execution:
  Arrange: No dummy files but create two empty directories.
  Act: Call the function with the paths to the empty directories as parameters.
  Assert: Check if the function returns empty lists for 'img_paths' and 'labels'.
Validation:
  This test is required to see how the function handles inputs where no files are to be parsed. The function, according to its definition, should handle this elegantly and return the empty list, indicating no files processed.

Scenario 4: Verifying the Function's Handling of Directories with Non-Matching Files
Details:
  TestName: test_NonMatchingFiles 
  Description: This test verifies how the function behaves when the label_dir contains files that don't match to any files in img_dir.
Execution:
  Arrange: Create dummy files in the label_dir which do not correspond to any image files in the img_dir.
  Act: Pass the directory paths as parameters to the method.
  Assert: The function should return list with the relative paths of the unmatched .txt files in 'img_paths' and their respective labels in 'labels', if any.
Validation:
  This test checks how well the function can handle situations where the label and image file names do not match. It is important that the function can still process these files and try to create a dataset as far as possible.

Scenario 5: Verifying the Correct Parsing of Label Data
Details:
  TestName: test_LabelDataParsing  
  Description: The test is meant to verify that the function correctly parses and represents GLOB data from a .txt file.
Execution:
  Arrange: Create dummy .txt files with known GLOB data. 
  Act: Pass the directory of the labels and the dummy image folder to the function.
  Assert: Check if the resulting label data is consistent with that of the dummy file, correctly parsing and formatting the content.
Validation:
  The parsed labels are essential in training machine learning models. It is important that the parsing and formatting of GLOB data is accurate, ensuring the correct representation of labels for images. It reassures that the function works as intended while using real data in production.
"""

# ********RoostGPT********
import pytest
import os
import glob
import random
from string import ascii_lowercase, digits
from pathlib import Path
try:
    from flip_augmentation import get_dataset
except ModuleNotFoundError:
    print("Make sure the python file is in the correct directory or installed as a package.")

class Test_FlipAugmentationGetDataset:
    
    def create_dummy_data(self, img_dir, label_dir, number_of_files=5):
        for _ in range(number_of_files):
            file_name = ''.join(random.choices(ascii_lowercase + digits, k=10))
            img_path = os.path.join(img_dir, f"{file_name}.jpg")
            label_path = os.path.join(label_dir, f"{file_name}.txt")
            
            with open(img_path, 'w') as img_file, open(label_path, 'w') as label_file:
                label_file.write("0 0.5 0.5 0.5 0.5")  # dummy bbox data
                
    @pytest.mark.smoke
    def test_FileParsingAndDatasetCreation(self):
        label_dir = Path(__file__).parent / 'labels'
        img_dir = Path(__file__).parent / 'images'
        label_dir.mkdir(parents=True, exist_ok=True)
        img_dir.mkdir(parents=True, exist_ok=True)
        
        self.create_dummy_data(img_dir, label_dir, number_of_files=5)
        
        img_paths, labels = get_dataset(str(label_dir), str(img_dir))
        assert len(img_paths) == len(labels) == 5
        
        # Delete dummy data
        for item in label_dir.glob('*'):
            item.unlink()
        for item in img_dir.glob('*'):
            item.unlink()
        img_dir.rmdir()
        label_dir.rmdir()

    @pytest.mark.smoke
    def test_NonexistentDirectories(self):
        img_dir = '/path/to/non/existent/img_dir'
        label_dir = '/path/to/non/existent/label_dir'
        img_paths, labels = get_dataset(label_dir, img_dir)
        assert len(img_paths) == len(labels) == 0

    @pytest.mark.smoke
    def test_EmptyDirectories(self):
        img_dir = Path(__file__).parent / 'empty_dir_images'
        label_dir = Path(__file__).parent / 'empty_dir_labels'
        img_dir.mkdir(parents=True, exist_ok=True)
        label_dir.mkdir(parents=True, exist_ok=True)
        
        img_paths, labels = get_dataset(str(label_dir), str(img_dir))
        assert len(img_paths) == len(labels) == 0
        
        img_dir.rmdir()
        label_dir.rmdir()

    @pytest.mark.smoke
    def test_NonMatchingFiles(self):
        img_dir = Path(__file__).parent / 'non_matching_images'
        label_dir = Path(__file__).parent / 'non_matching_labels'
        img_dir.mkdir(parents=True, exist_ok=True)
        label_dir.mkdir(parents=True, exist_ok=True)
        
        self.create_dummy_data(img_dir, label_dir, number_of_files=4)
           
        for i in range(2):
            file_name = ''.join(random.choices(ascii_lowercase + digits, k=10))
            label_path = os.path.join(label_dir, f"{file_name}.txt")
            with open(label_path, 'w') as label_file:
                label_file.write("0 0.5 0.5 0.5 0.5")  # dummy bbox data
                
        img_paths, labels = get_dataset(str(label_dir), str(img_dir))
        assert len(img_paths) == len(labels) == 4
        
        # Delete dummy data
        for item in label_dir.glob('*'):
            item.unlink()
        for item in img_dir.glob('*'):
            item.unlink()
        label_dir.rmdir()
        img_dir.rmdir()

    @pytest.mark.smoke
    def test_LabelDataParsing(self):
        label_dir = Path(__file__).parent / 'labels_check'
        img_dir = Path(__file__).parent / 'images_check'
        label_dir.mkdir(parents=True, exist_ok=True)
        img_dir.mkdir(parents=True, exist_ok=True)
        
        self.create_dummy_data(img_dir, label_dir, number_of_files=5)
        
        img_paths, labels = get_dataset(str(label_dir), str(img_dir))
        assert len(img_paths) == len(labels) == 5
        assert all(bbox == [0, 0.5, 0.5, 0.5, 0.5] for label in labels for bbox in label)
        
        # Delete dummy data
        for item in label_dir.glob('*'):
            item.unlink()
        for item in img_dir.glob('*'):
            item.unlink()
        img_dir.rmdir()
        label_dir.rmdir()
