# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=normalize_image_453f36db5d
ROOST_METHOD_SIG_HASH=normalize_image_95076f9de8


```
Scenario 1: Normalization of a non-zero, non-flattened matrix
Details:
  TestName: test_normalization_non_zero_matrix
  Description: This test is intended to verify that the function normalizes a 2D image array with diverse non-zero values appropriately.
Execution:
  Arrange: Define a 2D input array with a wide range of non-zero values not yet normalized.
  Act: Pass the defined array in function normalize_image without specifying cap and data_type.
  Assert: Check that the returned array has been correctly normalized to the uint8 range.
Validation:
  The function should be able to handle a diverse range of non-zero values across the 2D matrix and normalize them between 0 and 255. This test case validates this crucial operational expectation.

Scenario 2: Normalization with custom cap and data_type
Details:
  TestName: test_normalization_custom_cap_data_type
  Description: This test is to ensure that the function adheres to custom cap and data_type parameters.
Execution:
  Arrange: Define a 2D input array with non-normalized values. Specify non-default cap and data_type values.
  Act: Invoke the function normalize_image with the defined array, cap and data_type as arguments.
  Assert: The returned array should be normalized between 0 and the custom cap and be in the specified data format.
Validation:
  This test verifies the robustness of the function in handling custom cap and data_type parameters, which is a vital feature of this function.

Scenario 3: Normalization of a zero-value matrix
Details:
  TestName: test_normalization_zero_matrix
  Description: This test is to ensure the function correctly handles a 2D image array with zero values.
Execution:
  Arrange: Define a 2D input array filled with only zeros.
  Act: Invoke the function normalize_image with the zero-value matrix.
  Assert: The returned array should remain a zero-value matrix, as the normalization should not change this initial state.
Validation:
  This functionality is crucial since the image may contain large areas with zero-values (black), which implies that the function should handle this type of data and keep the same matrix after normalization.

Scenario 4: Handling of negative values in the input matrix
Details:
  TestName: test_normalization_negative_values
  Description: This test ensures that the function correctly normalizes a 2D image array with negative values.
Execution:
  Arrange: Define a 2D input array with negative and positive values.
  Act: Invoke the function normalize_image with the negative-valued matrix.
  Assert: The returned array should be normalized between 0 and cap, even though the original values were negative. 
Validation:
  It is important that the function can handle negative integers, as image processing may involve applying transformations that can result in negative pixel values before normalization. This test will validate that such data are handled correctly.
```
"""

# ********RoostGPT********
import numpy as np
import pytest
from haralick_descriptors import normalize_image

class Test_HaralickDescriptorsNormalizeImage:
    @pytest.mark.regression
    @pytest.mark.valid
    @pytest.mark.positive
    def test_normalization_non_zero_matrix(self):
        matrix = np.array([[45, 185, 77], [25, 12, 59]])
        expected = np.array([[63, 255, 121], [24, 0, 87]], dtype=np.uint8)
        output = normalize_image(matrix)
        assert np.array_equal(output, expected), f'Expected {expected}, but got {output}'

    @pytest.mark.regression
    @pytest.mark.valid
    @pytest.mark.positive
    def test_normalization_custom_cap_data_type(self):
        matrix = np.array([[45, 185, 77], [25, 12, 59]])
        cap_value = 1.0
        data_type_value = np.float64
        expected = np.array([[0.165, 1.0, 0.431], [0.083, 0.0, 0.32]], dtype=data_type_value)
        output = normalize_image(matrix, cap_value, data_type_value)
        np.testing.assert_allclose(output, expected, rtol=1e-05, atol=0), f'Expected {expected}, but got {output}'

    @pytest.mark.regression
    @pytest.mark.valid
    @pytest.mark.positive
    def test_normalization_zero_matrix(self):
        matrix = np.zeros((3, 3))
        expected = np.zeros((3, 3), dtype=np.uint8)
        output = normalize_image(matrix)
        assert np.array_equal(output, expected), f'Expected {expected}, but got {output}'

    @pytest.mark.regression
    @pytest.mark.valid
    @pytest.mark.positive
    def test_normalization_negative_values(self):
        matrix = np.array([[-5, -3, -1], [0, 5, 10]])
        expected = np.array([[0, 51, 102], [102, 204, 255]], dtype=np.uint8)
        output = normalize_image(matrix)
        assert np.array_equal(output, expected), f'Expected {expected}, but got {output}'
