# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonCVTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=get_distances_17a6331485
ROOST_METHOD_SIG_HASH=get_distances_166a6e990d


Scenario 1: Testing the function with a simple descriptor input and a valid base index
Details:
  TestName: test_get_distances_valid_input
  Description: This test will validate if the function correctly calculates the Euclidean distances between the descriptors.
Execution:
  Arrange: Desc_num=2 as the descriptors and base value as 1.
  Act: The function get_distances will be called with Desc_num descriptors and base value.
  Assert: The function should return a list of tuples of descriptor indices and their respective distances in decreasing order.
Validation:
  This test ensures that the basic functionality of the function is working properly.

Scenario 2: Testing the function with a negative base index
Details:
  TestName: test_get_distances_negative_base
  Description: The aim of the test is to validate the function's behavior when passed a negative base index.
Execution:
  Arrange: Escape_num=2 as descriptors and base value as -1.
  Act: The function get_distances will be invoked with Escape_num descriptors and base value.
  Assert: The function should return a list of tuples of descriptor indices and their respective distances in decreasing order computed using the last descriptor (due to negative index).
Validation:
  This validates the function's correctness in handling negative base index, an important feature of Python lists.

Scenario 3: Testing the function with base index equal to the length of descriptors
Details:
  TestName: test_get_distances_base_out_of_range
  Description: This test is designed to check the behavior of the function when the base index is equal to the length of the descriptors (which is out-of-range).
Execution:
  Arrange: Variable descriptors to be initialized with a 1D ndarray object of random values, and base index to be equal to the length of this array.
  Act: The function get_distances will be invoked with specified descriptors and base.
  Assert: The function should raise an IndexError.
Validation:
  The test validates how the function handles out of range indices, ensuring the function’s robustness.

Scenario 4: Testing the function with an empty descriptors array
Details:
  TestName: test_get_distances_empty_descriptors
  Description: This test is to validate the function's behavior when passed an empty descriptors array.
Execution:
  Arrange: Prepare an empty descriptors array and a base value of 0.
  Act: Call get_distances function with the prepared descriptors and base.
  Assert: The function should return an empty list since there are no descriptors to calculate the distance from.
Validation:
  The test ensures the function properly handles edge cases where there are no descriptors.

Scenario 5: Verify the function with a large descriptor array
Details:
  TestName: test_get_distances_large_input
  Description: This test is to verify how the function behaves with a large descriptor array.
Execution:
  Arrange: Prepare a large descriptor array and a valid base value.
  Act: Call get_distances function with the prepared descriptors and base.
  Assert: The function should successfully return a list of tuples reflecting the respective distances, without encountering any memory errors.
Validation:
  This test validates the function's efficiency and memory management capability when processing large arrays, which is crucial for realistic data processing scenarios.
"""

# ********RoostGPT********
import pytest
import imageio.v2 as imageio
import numpy as np
from haralick_descriptors import get_distances

class Test_HaralickDescriptorsGetDistances:

    @pytest.mark.regression
    def test_get_distances_valid_input(self):
        descriptors = np.array([[1,2,3],[4,5,6]])
        base = 1
        expected_output = [(0, np.sqrt(27)), (1, 0.0)]
        assert get_distances(descriptors, base) == expected_output

    @pytest.mark.regression
    def test_get_distances_negative_base(self):
        descriptors = np.array([[1,2,3],[4,5,6]])
        base = -1
        expected_output = [(0, np.sqrt(27)), (1, 0.0)]
        assert get_distances(descriptors, base) == expected_output

    @pytest.mark.regression
    def test_get_distances_base_out_of_range(self):
        descriptors = np.array([[1,2,3],[4,5,6]])
        base = len(descriptors)
        with pytest.raises(IndexError):
            get_distances(descriptors, base)

    @pytest.mark.regression
    def test_get_distances_empty_descriptors(self):
        descriptors = np.array([])
        base = 0
        with pytest.raises(IndexError):
            get_distances(descriptors, base)

    @pytest.mark.performance
    def test_get_distances_large_input(self):
        descriptors = np.random.rand(10000, 1000)
        base = 500
        assert isinstance(get_distances(descriptors, base), list)
